remote_theme: pages-themes/cayman@v0.2.0
title: DataDelver
description: Exploring the world of data, one delve at a time.

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
