site_name: DataDelver
site_url: https://www.datadelver.com
site_description: DataDelver is a blog about data science, machine learning, and artificial intelligence.
site_author: Chase Greco

theme:
  name: material
  icon:
    logo: material/pickaxe
  favicon: assets/images/favicon/pickaxe.png
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: blue
      accent: indigo

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
      primary: blue grey
      accent: deep purple
  
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
  
  custom_dir: overrides
plugins:
  - blog:
      blog_dir: .
      blog_toc: true
      post_url_format: "{slug}"
      post_excerpt: required
  - tags
  - search
  - social
  - meta
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - redirects:
      redirect_maps:
        'meta/2023/11/06/hello-labyrinth.md': 'posts/2023-11-06-hello-labyrinth.md'
        'ml engineering/2023/12/10/production-notebooks.md': 'posts/2023-12-10-production-notebooks.md'
        'ml engineering/data science/2023/12/23/ml-resources.md': 'posts/2023-12-23-ml-resources.md'
        'software engineering/2024/01/28/linux-fun.md': 'posts/2024-01-28-linux-fun.md'
        'ml engineering/2024/04/27/ml-engineer.md': 'posts/2024-04-27-ml-engineer.md'
        'software engineering/2024/06/29/pi-fullscreen.md': 'posts/2024-06-29-pi-fullscreen.md'
        'software engineering/2025/01/26/ml-micro-part-one.md': 'posts/2025-01-26-ml-micro-part-one.md'
        'software engineering/2025/02/05/ml-micro-part-two.md': 'posts/2025-02-05-ml-micro-part-two.md'
        'software engineering/2025/02/16/ml-micro-part-three.md': 'posts/2025-02-16-ml-micro-part-three.md'
        
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

use_directory_urls: false

extra:
  social:
    - icon: material/linkedin
      name: LinkedIn
      link: https://www.linkedin.com/in/chasegreco/
    - icon: /fontawesome/regular/envelope
      name: Email
      link: mailto:chase@datadelver.com
    - icon: material/github
      name: GitHub
      link: https://github.com/Zerthick