[project]
name = "datadelver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material>=9.6.7",
    "mkdocs-redirects>=1.2.2",
    "mkdocs-rss-plugin>=1.17.1",
]
