"""MkDocs plugin that sets page.meta['description'] from the blog post excerpt.

This ensures that both the HTML <meta name="description"> tag and the OG/Twitter
cards generated by the social plugin use the post excerpt instead of the
site-wide description.

The plugin runs on on_page_markdown with priority -60, which is after the blog
plugin's on_page_markdown (priority -50) so that page.excerpt is already created.
"""

import html
import re
from mkdocs.plugins import BasePlugin, event_priority

from .text_utils import (
    MD_LEADING_BLOCKQUOTE,
    YAML_FRONT_MATTER,
    strip_markdown,
)


class ExcerptDescriptionPlugin(BasePlugin):
    """Set page description from blog post excerpt."""

    @event_priority(-60)
    def on_page_markdown(self, markdown, *, page, config, files):
        # Only process blog posts (those with an excerpt attribute set by the blog plugin)
        if not hasattr(page, "excerpt") or page.excerpt is None:
            return

        # Get the excerpt separator from blog plugin config
        # Default is "<!-- more -->"
        separator = "<!-- more -->"
        if hasattr(page, "config") and hasattr(page.config, "post_excerpt_separator"):
            separator = page.config.post_excerpt_separator

        # Find the post in the blog plugin to get the separator
        # The blog plugin stores posts in config.plugins["blog"].config.blog.posts
        blog_plugin = config.plugins.get("blog")
        if blog_plugin:
            blog_config = blog_plugin.config
            separator = blog_config.post_excerpt_separator

        # Extract excerpt from page.markdown
        if separator in markdown:
            excerpt_md = markdown.split(separator, 1)[0]
        else:
            # Fallback: use the full markdown if separator not found
            excerpt_md = markdown

        # Strip YAML front matter
        excerpt_md = YAML_FRONT_MATTER.sub("", excerpt_md)

        # Strip the first heading (title) if present
        excerpt_md = re.sub(r"^#{1,6}\s+.*$", "", excerpt_md, count=1, flags=re.MULTILINE)

        # Strip leading blockquote (epigraph quote)
        excerpt_md = MD_LEADING_BLOCKQUOTE.sub("", excerpt_md)

        # Strip markdown formatting
        description = strip_markdown(excerpt_md)

        # Truncate to a reasonable length for meta descriptions (~160 chars is ideal)
        # but allow up to 320 chars to give more context
        max_length = 320
        if len(description) > max_length:
            # Truncate at word boundary
            description = description[:max_length].rsplit(" ", 1)[0]
            description += "..."

        # Set the description (escape HTML special chars for safe meta tag output)
        if description:
            page.meta["description"] = html.escape(description, quote=True)
