"""MkDocs plugin that sets page.meta['description'] from the blog post excerpt.

This ensures that both the HTML <meta name="description"> tag and the OG/Twitter
cards generated by the social plugin use the post excerpt instead of the
site-wide description.

The plugin runs on on_page_markdown with priority -60, which is after the blog
plugin's on_page_markdown (priority -50) so that page.excerpt is already created.
"""

import html
from mkdocs.plugins import BasePlugin, event_priority

from plugins.text_utils import extract_excerpt


class ExcerptDescriptionPlugin(BasePlugin):
    """Set page description from blog post excerpt."""

    @event_priority(-60)
    def on_page_markdown(self, markdown, *, page, config, files):
        # Only process blog posts (those with an excerpt attribute set by the blog plugin)
        if not hasattr(page, "excerpt") or page.excerpt is None:
            return

        # Get the excerpt separator from blog plugin config
        separator = "<!-- more -->"
        blog_plugin = config.plugins.get("blog")
        if blog_plugin:
            blog_config = blog_plugin.config
            separator = blog_config.post_excerpt_separator

        # Extract excerpt using shared utility
        description = extract_excerpt(markdown, separator=separator)

        # Truncate to a reasonable length for meta descriptions (~160 chars is ideal)
        # but allow up to 320 chars to give more context
        max_length = 320
        if len(description) > max_length:
            # Truncate at word boundary
            description = description[:max_length].rsplit(" ", 1)[0]
            description += "..."

        # Set the description (escape HTML special chars for safe meta tag output)
        if description:
            page.meta["description"] = html.escape(description, quote=True)
